apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../../../shared/postgres/user-db/overlays/staging
- ../../../../shared/redis/user-redis/overlays/staging
configMapGenerator:
- name: user-service-config
  envs:
  - params.env
secretGenerator:
- name: user-service-secrets
  envs:
  - secrets.env
patches:
- patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: user-service\n\
    spec:\n  replicas: 2\n  template:\n    spec:\n      containers:\n      - name:\
    \ user-service\n        resources:\n          requests:\n            memory: \"\
    512Mi\"\n            cpu: \"500m\"\n          limits:\n            memory: \"\
    1Gi\"\n            cpu: \"1000m\""
labels:
- pairs:
    environment: staging
  includeSelectors: true
