spring:
  cloud:
    aws:
      region:
        static: ${AWS_DEFAULT_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

  rabbitmq:
    listener:
      type: simple
      simple:
        auto-startup: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when_authorized 
  health:
    circuitbreakers:
      enabled: true
    redis:
      enabled: true
