spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  cloud:
    aws:
      region:
        static: sa-east-1
      credentials:
        access-key: "dev"
        secret-key: "dev"
      sqs:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*" 
  endpoint:
    health:
      show-details: always 
  health:
    circuitbreakers:
      enabled: true
    redis:
      enabled: true

