apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
labels:
- pairs:
    app: hermes
  includeSelectors: true
- pairs:
    managed-by: kustomize
  includeSelectors: true
