FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY bom/pom.xml bom/
COPY gateway/pom.xml gateway/

RUN sed -i '/<module>services\/user-service<\/module>/d' pom.xml

RUN chmod +x mvnw && ./mvnw dependency:go-offline -pl gateway -am -B

EXPOSE 8080

ENTRYPOINT ["./mvnw", "spring-boot:run", "-pl", "gateway"]
