apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- name: auth-postgres-config
  envs:
  - params.env
secretGenerator:
- name: auth-postgres-secrets
  envs:
  - secrets.env
patches:
- patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: auth-postgres\n\
    spec:\n  template:\n    spec:\n      containers:\n      - name: postgres\n   \
    \     resources:\n          requests:\n            memory: \"1Gi\"\n         \
    \   cpu: \"1000m\"\n          limits:\n            memory: \"2Gi\"\n         \
    \   cpu: \"2000m\""
- patch: "apiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: auth-postgres-data\n\
    spec:\n  resources:\n    requests:\n      storage: 50Gi"
labels:
- pairs:
    environment: prod
  includeSelectors: true
