management:
  endpoints:
    web:
      exposure:
        include: "*" 
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    redis:
      enabled: true
