management:
  endpoints:
    web:
      exposure:
        include: "*" 
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    redis:
      enabled: true

keycloak:
  server-url: ${KC_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}

