management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: none
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
    redis:
      enabled: true

cognito:
  user-pool-id: ${COGNITO_USER_POOL_ID}
  client-id: ${COGNITO_CLIENT_ID}
  client-secret: ${COGNITO_CLIENT_SECRET}
  domain-url: ${COGNITO_DOMAIN_URL}
  region: ${AWS_DEFAULT_REGION}

