apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- name: ws-gateway-config
  behavior: replace
  envs:
  - params.env
secretGenerator:
- name: ws-gateway-secrets
  envs:
  - secrets.env
labels:
- pairs:
    environment: dev
  includeSelectors: true
