apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-redis-data
  labels:
    app: auth-redis
    component: cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
