apiVersion: v1
kind: Service
metadata:
  name: auth-redis
  labels:
    app: auth-redis
    component: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: auth-redis
