apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: keycloak-realm-config
  files:
  - realm-export.json=realm-export.json
labels:
- pairs:
    app: keycloak
  includeSelectors: true
- pairs:
    managed-by: kustomize
  includeSelectors: true
