apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-postgres-data
  labels:
    app: auth-postgres
    component: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
