apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../../../shared/postgres/user-db/overlays/dev
- ../../../../shared/redis/user-redis/overlays/dev
configMapGenerator:
- name: user-service-config
  envs:
  - params.env
secretGenerator:
- name: user-service-secrets
  envs:
  - secrets.env
labels:
- pairs:
    environment: dev
  includeSelectors: true
