apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: "apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: hermes-ingress\n\
    spec:\n  rules:\n    - host: hermes-dev.local"
labels:
- pairs:
    environment: dev
  includeSelectors: true
