apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- name: ws-gateway-config
  behavior: replace
  envs:
  - params.env
secretGenerator:
- name: ws-gateway-secrets
  envs:
  - secrets.env
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ws-gateway
    spec:
      replicas: 3
      template:
        spec:
          containers:
          - name: ws-gateway
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
labels:
- pairs:
    environment: prod
  includeSelectors: true
