apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  labels:
    app: rabbitmq
    component: messaging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
