apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-postgres-data
  labels:
    app: user-postgres
    component: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
