apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-cache-data
  labels:
    app: gateway-cache
    component: cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
