#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $FLYWAY_USER WITH PASSWORD '$FLYWAY_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $FLYWAY_USER;
    GRANT ALL ON SCHEMA public TO $FLYWAY_USER;

    CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $APP_USER;
    GRANT USAGE ON SCHEMA public TO $APP_USER;
    
    ALTER DEFAULT PRIVILEGES FOR ROLE $FLYWAY_USER IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $APP_USER;
    ALTER DEFAULT PRIVILEGES FOR ROLE $FLYWAY_USER IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO $APP_USER;
EOSQL
