apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-redis-data
  labels:
    app: gateway-redis
    component: cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
