apiVersion: v1
kind: Service
metadata:
  name: scylladb
spec:
  ports:
  - port: 9042
    name: cql
    targetPort: 9042
  - port: 9160
    name: thrift
    targetPort: 9160
  - port: 10000
    name: rest
    targetPort: 10000
  selector:
    app: scylladb
  clusterIP: None
