apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: "apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: hermes-ingress\n\
    \  annotations:\n    cert-manager.io/cluster-issuer: letsencrypt-staging\n   \
    \ nginx.ingress.kubernetes.io/ssl-redirect: \"true\"\nspec:\n  tls:\n    - hosts:\n\
    \        - hermes-staging.yourdomain.com\n      secretName: hermes-staging-tls\n\
    \  rules:\n    - host: hermes-staging.yourdomain.com"
labels:
- pairs:
    environment: staging
  includeSelectors: true
