apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../shared/rabbitmq/overlays/staging
- ../../shared/nats/overlays/staging
- ../../shared/keycloak/overlays/staging
- ../../shared/ingress/overlays/staging
- ../../shared/observability/base

- ../../services/auth-service/overlays/staging
- ../../services/user-service/overlays/staging
- ../../gateways/http-gateway/overlays/staging
- ../../gateways/ws-gateway/overlays/staging

namespace: hermes-staging
labels:
- pairs:
    environment: staging
  includeSelectors: true
- pairs:
    cluster: staging
  includeSelectors: true
- pairs:
    managed-by: kustomize
  includeSelectors: true
