apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: gateway-redis\n\
    spec:\n  replicas: 3\n  template:\n    spec:\n      containers:\n      - name:\
    \ redis\n        resources:\n          requests:\n            memory: \"512Mi\"\
    \n            cpu: \"500m\"\n          limits:\n            memory: \"1Gi\"\n\
    \            cpu: \"1000m\""
- patch: "apiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: gateway-redis-data\n\
    spec:\n  resources:\n    requests:\n      storage: 10Gi"
labels:
- pairs:
    environment: prod
  includeSelectors: true
