apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../../../shared/redis/gateway-cache/overlays/prod
configMapGenerator:
- name: gateway-config
  envs:
  - params.env
secretGenerator:
- name: gateway-secrets
  envs:
  - secrets.env
patches:
- patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: api-gateway\n\
    spec:\n  replicas: 3\n  template:\n    spec:\n      containers:\n      - name:\
    \ api-gateway\n        resources:\n          requests:\n            memory: \"\
    1Gi\"\n            cpu: \"1000m\"\n          limits:\n            memory: \"2Gi\"\
    \n            cpu: \"2000m\""
labels:
- pairs:
    environment: prod
  includeSelectors: true
