apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-data
  labels:
    app: nats
    component: messaging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
